export interface TokenDefinition {
  symbol: string
  name: string
  keywords: string[]
  rank: number
  marketCapTier: string
}

export const TOP_TOKENS: TokenDefinition[] = [
  { symbol: "BTC",   name: "Bitcoin",          rank: 1,  marketCapTier: "MEGA",  keywords: ["bitcoin","btc","satoshi","lightning network","halving","bitcoin etf"] },
  { symbol: "ETH",   name: "Ethereum",         rank: 2,  marketCapTier: "MEGA",  keywords: ["ethereum","eth","ether","vitalik","buterin","eip","merge","dencun"] },
  { symbol: "BNB",   name: "BNB",              rank: 3,  marketCapTier: "LARGE", keywords: ["bnb","binance coin","bsc","binance smart chain"] },
  { symbol: "SOL",   name: "Solana",           rank: 4,  marketCapTier: "LARGE", keywords: ["solana","sol","solana labs","firedancer"] },
  { symbol: "XRP",   name: "XRP",              rank: 5,  marketCapTier: "LARGE", keywords: ["xrp","ripple","ripplenet","sec ripple"] },
  { symbol: "USDC",  name: "USD Coin",         rank: 6,  marketCapTier: "MEGA",  keywords: ["usdc","usd coin","circle"] },
  { symbol: "ADA",   name: "Cardano",          rank: 7,  marketCapTier: "LARGE", keywords: ["cardano","ada","iohk","hoskinson"] },
  { symbol: "AVAX",  name: "Avalanche",        rank: 8,  marketCapTier: "LARGE", keywords: ["avalanche","avax","subnet","ava labs"] },
  { symbol: "DOGE",  name: "Dogecoin",         rank: 9,  marketCapTier: "LARGE", keywords: ["dogecoin","doge","meme coin"] },
  { symbol: "TRX",   name: "TRON",             rank: 10, marketCapTier: "LARGE", keywords: ["tron","trx","justin sun"] },
  { symbol: "DOT",   name: "Polkadot",         rank: 11, marketCapTier: "LARGE", keywords: ["polkadot","dot","parachain","substrate"] },
  { symbol: "MATIC", name: "Polygon",          rank: 12, marketCapTier: "LARGE", keywords: ["polygon","matic","pol","zkevm"] },
  { symbol: "LINK",  name: "Chainlink",        rank: 13, marketCapTier: "LARGE", keywords: ["chainlink","link","oracle"] },
  { symbol: "SHIB",  name: "Shiba Inu",        rank: 14, marketCapTier: "MID",   keywords: ["shib","shiba inu","shibarium"] },
  { symbol: "LTC",   name: "Litecoin",         rank: 15, marketCapTier: "LARGE", keywords: ["litecoin","ltc"] },
  { symbol: "UNI",   name: "Uniswap",          rank: 16, marketCapTier: "LARGE", keywords: ["uniswap","uni","dex amm"] },
  { symbol: "ATOM",  name: "Cosmos",           rank: 17, marketCapTier: "LARGE", keywords: ["cosmos","atom","ibc","tendermint"] },
  { symbol: "ARB",   name: "Arbitrum",         rank: 18, marketCapTier: "LARGE", keywords: ["arbitrum","arb","layer 2"] },
  { symbol: "OP",    name: "Optimism",         rank: 19, marketCapTier: "LARGE", keywords: ["optimism","op","optimistic rollup"] },
  { symbol: "NEAR",  name: "NEAR Protocol",    rank: 20, marketCapTier: "LARGE", keywords: ["near","near protocol"] },
  { symbol: "AAVE",  name: "Aave",             rank: 21, marketCapTier: "LARGE", keywords: ["aave","lending protocol","flash loan"] },
  { symbol: "MKR",   name: "Maker",            rank: 22, marketCapTier: "MID",   keywords: ["maker","mkr","makerdao","dai"] },
  { symbol: "LDO",   name: "Lido DAO",         rank: 23, marketCapTier: "LARGE", keywords: ["lido","ldo","liquid staking","steth"] },
  { symbol: "TON",   name: "Toncoin",          rank: 24, marketCapTier: "LARGE", keywords: ["ton","toncoin","telegram"] },
  { symbol: "SUI",   name: "Sui",              rank: 25, marketCapTier: "LARGE", keywords: ["sui","mysten labs"] },
  { symbol: "TIA",   name: "Celestia",         rank: 26, marketCapTier: "MID",   keywords: ["celestia","tia","modular blockchain","data availability"] },
  { symbol: "JUP",   name: "Jupiter",          rank: 27, marketCapTier: "LARGE", keywords: ["jupiter","jup","solana dex"] },
  { symbol: "WIF",   name: "dogwifhat",        rank: 28, marketCapTier: "MID",   keywords: ["dogwifhat","wif"] },
  { symbol: "PEPE",  name: "Pepe",             rank: 29, marketCapTier: "MID",   keywords: ["pepe","pepe coin"] },
  { symbol: "WLD",   name: "Worldcoin",        rank: 30, marketCapTier: "MID",   keywords: ["worldcoin","wld","world id","sam altman"] },
  { symbol: "ONDO",  name: "Ondo",             rank: 31, marketCapTier: "MID",   keywords: ["ondo","rwa","real world assets","tokenized"] },
  { symbol: "ENA",   name: "Ethena",           rank: 32, marketCapTier: "MID",   keywords: ["ethena","ena","usde","synthetic dollar"] },
  { symbol: "STRK",  name: "StarkNet",         rank: 33, marketCapTier: "MID",   keywords: ["starknet","strk","cairo"] },
  { symbol: "EIGEN", name: "EigenLayer",       rank: 34, marketCapTier: "MID",   keywords: ["eigenlayer","eigen","restaking"] },
  { symbol: "PENDLE",name: "Pendle",           rank: 35, marketCapTier: "MID",   keywords: ["pendle","yield trading"] },
  { symbol: "DYDX",  name: "dYdX",             rank: 36, marketCapTier: "MID",   keywords: ["dydx","perpetual","derivatives dex"] },
  { symbol: "ORDI",  name: "ORDI",             rank: 37, marketCapTier: "MID",   keywords: ["ordi","ordinals","brc-20","inscription"] },
  { symbol: "STX",   name: "Stacks",           rank: 38, marketCapTier: "MID",   keywords: ["stacks","stx","bitcoin defi"] },
  { symbol: "SEI",   name: "Sei",              rank: 39, marketCapTier: "MID",   keywords: ["sei","sei network"] },
  { symbol: "HBAR",  name: "Hedera",           rank: 40, marketCapTier: "MID",   keywords: ["hedera","hbar","hashgraph"] },
  { symbol: "ICP",   name: "Internet Computer",rank: 41, marketCapTier: "MID",   keywords: ["internet computer","icp","dfinity"] },
  { symbol: "FTM",   name: "Fantom",           rank: 42, marketCapTier: "MID",   keywords: ["fantom","ftm","sonic"] },
  { symbol: "INJ",   name: "Injective",        rank: 43, marketCapTier: "MID",   keywords: ["injective","inj"] },
  { symbol: "GRT",   name: "The Graph",        rank: 44, marketCapTier: "MID",   keywords: ["the graph","grt","subgraph"] },
  { symbol: "GMX",   name: "GMX",              rank: 45, marketCapTier: "MID",   keywords: ["gmx","glp","arbitrum perpetual"] },
  { symbol: "BLUR",  name: "Blur",             rank: 46, marketCapTier: "MID",   keywords: ["blur","nft marketplace"] },
  { symbol: "IMX",   name: "Immutable",        rank: 47, marketCapTier: "MID",   keywords: ["immutable","imx","nft gaming"] },
  { symbol: "ALGO",  name: "Algorand",         rank: 48, marketCapTier: "MID",   keywords: ["algorand","algo"] },
  { symbol: "VET",   name: "VeChain",          rank: 49, marketCapTier: "MID",   keywords: ["vechain","vet","supply chain","vtho"] },
  { symbol: "XMR",   name: "Monero",           rank: 50, marketCapTier: "MID",   keywords: ["monero","xmr","privacy coin"] },
]

export const MARKET_CAP_WEIGHTS: Record<string, number> = {
  MEGA:  1.0,
  LARGE: 0.75,
  MID:   0.5,
  SMALL: 0.25,
}

export const NARRATIVE_KEYWORDS: Record<string, number> = {
  hack: 0.9,
  exploit: 0.9,
  breach: 0.85,
  hacked: 0.9,
  stolen: 0.8,
  sec: 0.8,
  lawsuit: 0.75,
  regulation: 0.7,
  regulatory: 0.7,
  ban: 0.85,
  etf: 0.8,
  approval: 0.75,
  rejected: 0.75,
  listing: 0.7,
  delisting: 0.9,
  partnership: 0.6,
  acquisition: 0.7,
  bankrupt: 0.95,
  insolvent: 0.95,
  scam: 0.95,
  fraud: 0.9,
  liquidation: 0.85,
  whale: 0.65,
  dump: 0.8,
  pump: 0.75,
  airdrop: 0.6,
  mainnet: 0.65,
  upgrade: 0.6,
  fork: 0.7,
  halving: 0.8,
  institutional: 0.65,
  treasury: 0.6,
  launch: 0.55,
  integration: 0.55,
}
