// Top 200 token keywords for entity extraction
// Extend this list as needed

export const TOP_TOKENS = [
  { symbol: 'BTC',   name: 'Bitcoin',          keywords: ['bitcoin','btc','satoshi','lightning','halving','sats'] },
  { symbol: 'ETH',   name: 'Ethereum',          keywords: ['ethereum','eth','vitalik','erc20','erc-20','merge','dencun','beacon'] },
  { symbol: 'USDT',  name: 'Tether',            keywords: ['tether','usdt','stablecoin'] },
  { symbol: 'BNB',   name: 'BNB',               keywords: ['bnb','binance coin','bsc','binance smart chain','cz'] },
  { symbol: 'SOL',   name: 'Solana',            keywords: ['solana','sol','firedancer','sealevel'] },
  { symbol: 'USDC',  name: 'USDC',              keywords: ['usdc','usd coin','circle'] },
  { symbol: 'XRP',   name: 'XRP',               keywords: ['xrp','ripple','brad garlinghouse'] },
  { symbol: 'DOGE',  name: 'Dogecoin',          keywords: ['dogecoin','doge'] },
  { symbol: 'TON',   name: 'Toncoin',           keywords: ['toncoin','ton','telegram'] },
  { symbol: 'ADA',   name: 'Cardano',           keywords: ['cardano','ada','hoskinson'] },
  { symbol: 'AVAX',  name: 'Avalanche',         keywords: ['avalanche','avax','subnet'] },
  { symbol: 'TRX',   name: 'TRON',              keywords: ['tron','trx','justin sun'] },
  { symbol: 'SHIB',  name: 'Shiba Inu',         keywords: ['shiba inu','shib'] },
  { symbol: 'DOT',   name: 'Polkadot',          keywords: ['polkadot','dot','parachain','gavin wood'] },
  { symbol: 'LINK',  name: 'Chainlink',         keywords: ['chainlink','link','oracle'] },
  { symbol: 'MATIC', name: 'Polygon',           keywords: ['polygon','matic'] },
  { symbol: 'LTC',   name: 'Litecoin',          keywords: ['litecoin','ltc'] },
  { symbol: 'BCH',   name: 'Bitcoin Cash',      keywords: ['bitcoin cash','bch'] },
  { symbol: 'UNI',   name: 'Uniswap',           keywords: ['uniswap','uni'] },
  { symbol: 'NEAR',  name: 'NEAR Protocol',     keywords: ['near protocol','near'] },
  { symbol: 'ATOM',  name: 'Cosmos',            keywords: ['cosmos','atom','ibc','osmosis'] },
  { symbol: 'APT',   name: 'Aptos',             keywords: ['aptos','apt'] },
  { symbol: 'ICP',   name: 'Internet Computer', keywords: ['internet computer','icp','dfinity'] },
  { symbol: 'XLM',   name: 'Stellar',           keywords: ['stellar','xlm','lumens'] },
  { symbol: 'FIL',   name: 'Filecoin',          keywords: ['filecoin','fil'] },
  { symbol: 'ARB',   name: 'Arbitrum',          keywords: ['arbitrum','arb'] },
  { symbol: 'OP',    name: 'Optimism',          keywords: ['optimism','op'] },
  { symbol: 'HBAR',  name: 'Hedera',            keywords: ['hedera','hbar','hashgraph'] },
  { symbol: 'CRO',   name: 'Cronos',            keywords: ['cronos','cro','crypto.com'] },
  { symbol: 'STX',   name: 'Stacks',            keywords: ['stacks','stx'] },
  { symbol: 'MNT',   name: 'Mantle',            keywords: ['mantle','mnt'] },
  { symbol: 'VET',   name: 'VeChain',           keywords: ['vechain','vet'] },
  { symbol: 'ALGO',  name: 'Algorand',          keywords: ['algorand','algo'] },
  { symbol: 'EGLD',  name: 'MultiversX',        keywords: ['multiversx','egld','elrond'] },
  { symbol: 'SAND',  name: 'The Sandbox',       keywords: ['sandbox','sand','metaverse'] },
  { symbol: 'MANA',  name: 'Decentraland',      keywords: ['decentraland','mana'] },
  { symbol: 'AAVE',  name: 'Aave',              keywords: ['aave','defi','lending'] },
  { symbol: 'GRT',   name: 'The Graph',         keywords: ['the graph','grt'] },
  { symbol: 'SNX',   name: 'Synthetix',         keywords: ['synthetix','snx'] },
  { symbol: 'MKR',   name: 'Maker',             keywords: ['maker','mkr','dai','makerdao'] },
  { symbol: 'CRV',   name: 'Curve',             keywords: ['curve','crv','curve finance'] },
  { symbol: 'LDO',   name: 'Lido DAO',          keywords: ['lido','ldo','staking'] },
  { symbol: 'RNDR',  name: 'Render',            keywords: ['render','rndr','gpu'] },
  { symbol: 'INJ',   name: 'Injective',         keywords: ['injective','inj'] },
  { symbol: 'SUI',   name: 'Sui',               keywords: ['sui','mysten'] },
  { symbol: 'SEI',   name: 'Sei',               keywords: ['sei network','sei'] },
  { symbol: 'PEPE',  name: 'Pepe',              keywords: ['pepe','meme coin'] },
  { symbol: 'WIF',   name: 'Dogwifhat',         keywords: ['dogwifhat','wif'] },
  { symbol: 'BONK',  name: 'Bonk',              keywords: ['bonk'] },
  { symbol: 'JUP',   name: 'Jupiter',           keywords: ['jupiter','jup'] },
] as const
